export const participantList = [
    {
        id:"0",
      playerName: "阿強",
      playerTotalTrials: 12,
      isFriend: true,
      playerImgUrl: "/avatar/girlJacketBandage.webp",
      likedPosts:2,
      friends:15,
    },
    {
        id:"1",
      playerName: "小美",
      playerTotalTrials: 27,
      isFriend: false,
      playerImgUrl: "/avatar/girlSkirtBubble.webp",
      likedPosts:5,
      friends:32,
    },
    {
        id:"2",
      playerName: "獵魔士Geralt",
      playerTotalTrials: 42,
      isFriend: true,
      playerImgUrl: "/avatar/girlJacketYoga.webp",
      likedPosts:23,
      friends:53,
    },
    {
        id:"3",
      playerName: "貓貓教主",
      playerTotalTrials: 9,
      isFriend: false,
      playerImgUrl: "/avatar/girlPurpleHeadphone.webp",
      likedPosts:10,
      friends:23,
    },
    {
        id:"4",
      playerName: "雷姆",
      playerTotalTrials: 15,
      isFriend: false,
      playerImgUrl: "/avatar/girlBearJacket.webp",
      likedPosts:0,
      friends:2,
    },
  ];